/**
 * Curated Pre-configured Investment Journey Templates
 */

export const PRESETS = [
  {
    id: 'core-demo',
    title: 'Timeline Showcase (Prompt Default)',
    description: 'Initial ₹10L + ₹25k SIP + 3 mid-journey lumpsums (M12, M30, M60)',
    config: {
      horizonYears: 10,
      expectedAnnualReturn: 12.0,
      inflationRate: 6.0,
      compoundingFrequency: 'monthly',
      initialInvestment: 1000000,
      events: [
        {
          id: 'sip-1',
          name: 'Monthly Core SIP',
          type: 'sip',
          amount: 25000,
          startMonth: 1,
          endMonth: 120,
          stepUpPercent: 0,
          isPaused: false,
          enabled: true,
        },
        {
          id: 'lump-1',
          name: 'Bonus Inflow',
          type: 'lumpsum',
          amount: 200000,
          month: 12,
          enabled: true,
        },
        {
          id: 'lump-2',
          name: 'Property Gain Injection',
          type: 'lumpsum',
          amount: 500000,
          month: 30,
          enabled: true,
        },
        {
          id: 'lump-3',
          name: 'Matured FD Rollover',
          type: 'lumpsum',
          amount: 300000,
          month: 60,
          enabled: true,
        },
      ],
      yearReturnOverrides: {},
    },
  },
  {
    id: 'accumulation-swp',
    title: 'Accumulation → Retirement SWP',
    description: '10 Years accumulation followed by ₹50k/month SWP with 5% annual raise',
    config: {
      horizonYears: 15,
      expectedAnnualReturn: 12.0,
      inflationRate: 6.0,
      compoundingFrequency: 'monthly',
      initialInvestment: 500000,
      events: [
        {
          id: 'sip-accum',
          name: 'Accumulation SIP',
          type: 'sip',
          amount: 35000,
          startMonth: 1,
          endMonth: 120,
          stepUpPercent: 8,
          isPaused: false,
          enabled: true,
        },
        {
          id: 'lump-mid',
          name: 'Mid-Career Windfall',
          type: 'lumpsum',
          amount: 600000,
          month: 60,
          enabled: true,
        },
        {
          id: 'swp-retire',
          name: 'Retirement Monthly SWP',
          type: 'swp',
          amount: 60000,
          startMonth: 121,
          durationMonths: 60,
          stepUpPercent: 5,
          enabled: true,
        },
      ],
      yearReturnOverrides: {},
    },
  },
  {
    id: 'step-up-wealth',
    title: 'High Octane 10% Step-Up SIP',
    description: 'Starting ₹20k/mo with 10% annual escalation and mid-term booster',
    config: {
      horizonYears: 12,
      expectedAnnualReturn: 13.5,
      inflationRate: 6.0,
      compoundingFrequency: 'monthly',
      initialInvestment: 300000,
      events: [
        {
          id: 'sip-stepup',
          name: 'Escalating Career SIP',
          type: 'sip',
          amount: 20000,
          startMonth: 1,
          endMonth: 144,
          stepUpPercent: 10,
          isPaused: false,
          enabled: true,
        },
        {
          id: 'lump-prom',
          name: 'Promotion Bonus',
          type: 'lumpsum',
          amount: 400000,
          month: 48,
          enabled: true,
        },
        {
          id: 'lump-prom2',
          name: 'Equity ESOP Liquidation',
          type: 'lumpsum',
          amount: 800000,
          month: 96,
          enabled: true,
        },
      ],
      yearReturnOverrides: {},
    },
  },
  {
    id: 'conservative-fire',
    title: 'Conservative Capital Preservation',
    description: '₹25L Initial Lumpsum, ₹15k monthly SIP, conservative 9% returns',
    config: {
      horizonYears: 10,
      expectedAnnualReturn: 9.0,
      inflationRate: 5.5,
      compoundingFrequency: 'monthly',
      initialInvestment: 2500000,
      events: [
        {
          id: 'sip-debt',
          name: 'Disciplined Debt/Equity SIP',
          type: 'sip',
          amount: 15000,
          startMonth: 1,
          endMonth: 120,
          stepUpPercent: 5,
          isPaused: false,
          enabled: true,
        },
      ],
      yearReturnOverrides: {},
    },
  },
];
